# Generated by Django 5.2.5 on 2025-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tickettype_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
