# Generated by Django 5.2.5 on 2025-08-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_tickettype_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='quantity',
        ),
    ]
