# Generated by Django 5.2.5 on 2025-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancled', 'Cancled')], db_index=True, default='upcoming', max_length=20),
        ),
    ]
