# Generated by Django 5.2.5 on 2025-10-24 18:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_is_published_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancled', 'Cancled')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
