# Generated by Django 5.2.5 on 2025-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_event_image_alter_event_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.category'),
        ),
    ]
