# Generated by Django 5.2.5 on 2026-06-14 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dot_color', models.CharField(choices=[('var(--amber)', 'Amber'), ('var(--green)', 'Green'), ('var(--blue)', 'Blue'), ('var(--brand)', 'Brand'), ('var(--red)', 'Red')], default='var(--blue)', max_length=30)),
                ('html_text', models.TextField(help_text='Stores pre-formatted HTML snippet for HTMX display')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
