# Generated by Django 5.2.5 on 2025-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_organizer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
