# Generated by Django 5.2.5 on 2025-09-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_about_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
