# Generated by Django 5.2.5 on 2026-06-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_organizerapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organizer',
        ),
    ]
