# Generated by Django 5.2.5 on 2026-06-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_is_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ATTENDEE', 'Attendee'), ('ORGANIZER', 'Organizer'), ('VALIDATOR', 'Validator'), ('MODERATOR', 'Moderator')], default='ATTENDEE', max_length=20),
        ),
    ]
