# Generated by Django 5.2.5 on 2026-06-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_validator',
            field=models.BooleanField(default=False),
        ),
    ]
